apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: demo-api
  description: The machine-readable interface for my first app
spec:
  type: openapi
  lifecycle: experimental
  owner: group:default/team-a
  definition: |
    openapi: 3.0.0
    info:
      title: Demo API
      version: 1.0.0
    paths:
      /hello:
        get:
          summary: Say hello to the machine
          responses:
            '200':
              description: A successful response
